on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test JLineup Workflow
    steps:
      - uses: actions/checkout@v3
      - name: Run JLineup before
        uses: ./ # Uses an action in the root directory
        id: jlineup_before
        with:
          step: before
      - name: Get the result from JLineup before step
        run: echo "${{ steps.jlineup_before.outputs.result }}"
      - name: Run JLineup after
        uses: ./ # Uses an action in the root directory
        id: jlineup_after
        with:
          step: after
      - name: Get the result from JLineup after step
        run: echo "${{ steps.jlineup_after.outputs.result }}"
      - name: Get the difference sum
        run: echo ${{ steps.jlineup_after.outputs.difference }}
      - name: Get the success indicator
        run: echo ${{ steps.jlineup_after.outputs.success }}
      - name: Archive JLineup report
        uses: actions/upload-artifact@v3
        with:
          name: JLineup Report
          path: ${{ steps.jlineup_before.outputs.workspace }}/report
